export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
